name : Wrokflow 1. 
'on': push

jobs:
  build :
    name : Build
    runs-on : [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    # Steps:
    steps:
      - name : Checkout Code
        uses : actions/checkout@v2
        
      - name : install Node version
        uses : actions/setup-node@v1
        with :
          node-version: 16.x
      - name : Install npm Dependencies #Eg(React icon ,React Dom etc....)
        run : npm install
      - name : Building Project 
        run : npm run build
#       - name: Upload artifact in order to deploy
#         uses: actions/upload-artifact@v2
#         with:
#           name: production-files
#           path: ./dist
  # Test Job
  test :
    name : Test
    runs-on : [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    needs : build

    steps :
      - name : Testing test Cases for frontend
        uses : npm test
 # Deploy Job
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux, x64, philips-code-hub, ubuntu-latest]
    needs: build

    steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: production-files
#           path: ./dist
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACC_TKN }}
          publish_dir: ./dist
  


  
    
